name: client-c++

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services:
      model:
        image: linusseelinger/model-testmodel:latest
        ports:
        - 4242:4242

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update; DEBIAN_FRONTEND="noninteractive" apt install -y g++ libeigen3-dev libssl-dev
       -
        name: Build and run
        run: |
          cd clients/c++ && ./build.sh && ./http-client model:4242
