name: client-python

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services:
      model:
        image: linusseelinger/model-testmodel:latest
        ports:
        - 4242:4242

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update && DEBIAN_FRONTEND="noninteractive" apt install -y python3-pip && pip3 install requests aiohttp
       -
        name: Build and run
        run: |
          cd clients/python && python3 http-client.py http://model:4242
