name: client-c++

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services:
      model:
        image: linusseelinger/benchmark-analytic-banana:latest
        ports:
        - 4243:4243

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update; DEBIAN_FRONTEND="noninteractive" apt install -y g++ libssl-dev
       -
        name: Build and run
        run: |
          cd clients/c++ && ./build.sh && ./http-client model:4243
