name: poisson-mi

on:
  push:
    branches:
      - 'main'

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: models/poisson-mi/
#          push: true
#          tags: linusseelinger/poisson-mi:latest

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    #needs: build

    services:
      model:
        image: linusseelinger/poisson-mi:latest
        ports:
        - 4242:4242
        #- 4242/tcp

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: GetInputSizes
        run: |
          apt update; apt install curl; if [ "$(curl model:4242/GetInputSizes)" != "{\"inputSizes\":[4]}" ]; then exit 1; fi
       -
        name: GetInputSizesFalse
        run: |
          if [ "$(curl http://model:4242/GetInputSizes)" == "{\"inputSizes\":[4]}" ]; then exit 1; fi
